services:
  stash-telegram-bot:
    container_name: stash-telegram-bot
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    environment:
      - TZ=Europe/Moscow
      - LOG_PATH=/dev/null
      # Пример: если используете webhook, можно задать внешний порт через переменную
      # - WEBHOOK_PORT=8443
    healthcheck:
      interval: 60s
      retries: 3
      start_period: 30s
      test:
        - CMD
        - python
        - /app/healthcheck.py
      timeout: 10s
    image: ghcr.io/frendly/stashapptelegrambot:latest
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    restart: unless-stopped
    user: '568:568'
    # Пример проброса порта для webhook:
    # внутри контейнера бот по умолчанию слушает на 8443 (telegram.webhook.port),
    # а снаружи TrueNAS будет доступен на WEBHOOK_PORT (например 8443 или 30443).
    #ports:
    #  - "${WEBHOOK_PORT:-8443}:8443"
    volumes:
      - read_only: True
        source: /mnt/apps/stash-telegram-bot/config
        target: /config
        type: bind
      - read_only: False
        source: /mnt/apps/stash-telegram-bot/data
        target: /data
        type: bind
  watchtower:
    command: stash-telegram-bot
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_MONITOR_ONLY=false
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
version: '3.8'
